// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwmibpzmwxacpoffxqri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53bWlicHptd3hhY3BvZmZ4cXJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNjQ3MjksImV4cCI6MjA2NTk0MDcyOX0._x5l6gjMtWEZ-QWP89b6Y_80ODy91H6vNVBr_-lPrec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);